CONFIG_GPIO=y

# UART
CONFIG_UART_INTERRUPT_DRIVEN=y

# CAN
CONFIG_CAN=y
CONFIG_CAN_MCP2515=y
CONFIG_SPI=y

# GNSS
CONFIG_GNSS=y
CONFIG_GNSS_NMEA_GENERIC=y
CONFIG_GNSS_SATELLITES=y

# Logging
CONFIG_LOG=y
CONFIG_GNSS_DUMP_TO_LOG=y